/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalhanaval;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author l a w t
 */
public class Jogo extends javax.swing.JFrame {

    /**
     * Creates new form Jogo
     */
    public Jogo() {

        initComponents();

        for (int l = 0; l < 5; l++) {
            for (int c = 0; c < 10; c++) {
                Fundo.add(CriarQuadrados1(c, l));
                Fundo.add(CriarQuadrados2(c, l));
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PortaAvioes = new javax.swing.ButtonGroup();
        Fragata = new javax.swing.ButtonGroup();
        Cruzador = new javax.swing.ButtonGroup();
        Fundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        cruzadortxt = new javax.swing.JLabel();
        posInicialtxt = new javax.swing.JLabel();
        Fcruzador = new javax.swing.JTextField();
        portaavioestxt = new javax.swing.JLabel();
        fragatatxt = new javax.swing.JLabel();
        FportaAvioes = new javax.swing.JTextField();
        Ffragata = new javax.swing.JTextField();
        VportaA = new javax.swing.JRadioButton();
        HportaA = new javax.swing.JRadioButton();
        Hfragata = new javax.swing.JRadioButton();
        Vfragata = new javax.swing.JRadioButton();
        Hcruzador = new javax.swing.JRadioButton();
        Vcruzador = new javax.swing.JRadioButton();
        IniciarB = new javax.swing.JButton();
        closeB = new javax.swing.JLabel();
        AtacarB = new javax.swing.JButton();
        Fataque = new javax.swing.JTextField();
        disparartxt = new javax.swing.JLabel();
        exTxt = new javax.swing.JLabel();
        exTxt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Fundo.setBackground(new java.awt.Color(51, 51, 51));
        Fundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Fundo.setForeground(new java.awt.Color(102, 204, 0));
        Fundo.setPreferredSize(new java.awt.Dimension(888, 600));
        Fundo.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("1");
        Fundo.add(jLabel1);
        jLabel1.setBounds(53, 9, 12, 26);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("2");
        Fundo.add(jLabel2);
        jLabel2.setBounds(105, 9, 12, 26);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("3");
        Fundo.add(jLabel3);
        jLabel3.setBounds(153, 9, 12, 26);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("4");
        Fundo.add(jLabel4);
        jLabel4.setBounds(200, 9, 12, 26);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("5");
        Fundo.add(jLabel5);
        jLabel5.setBounds(247, 9, 12, 26);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("6");
        Fundo.add(jLabel6);
        jLabel6.setBounds(299, 9, 12, 26);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("7");
        Fundo.add(jLabel7);
        jLabel7.setBounds(351, 9, 12, 26);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("8");
        Fundo.add(jLabel8);
        jLabel8.setBounds(399, 9, 12, 26);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("9");
        Fundo.add(jLabel9);
        jLabel9.setBounds(451, 9, 12, 26);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("10");
        Fundo.add(jLabel10);
        jLabel10.setBounds(495, 9, 24, 26);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("A");
        Fundo.add(jLabel21);
        jLabel21.setBounds(8, 48, 14, 26);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("B");
        Fundo.add(jLabel22);
        jLabel22.setBounds(8, 98, 14, 26);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("C");
        Fundo.add(jLabel23);
        jLabel23.setBounds(8, 148, 14, 26);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("D");
        Fundo.add(jLabel24);
        jLabel24.setBounds(8, 198, 14, 26);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("E");
        Fundo.add(jLabel25);
        jLabel25.setBounds(8, 248, 13, 26);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("E");
        Fundo.add(jLabel26);
        jLabel26.setBounds(9, 530, 13, 26);

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("D");
        Fundo.add(jLabel27);
        jLabel27.setBounds(9, 486, 14, 26);

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("C");
        Fundo.add(jLabel28);
        jLabel28.setBounds(9, 434, 14, 26);

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("B");
        Fundo.add(jLabel29);
        jLabel29.setBounds(9, 380, 14, 26);

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("A");
        Fundo.add(jLabel30);
        jLabel30.setBounds(9, 336, 14, 26);

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("1");
        Fundo.add(jLabel31);
        jLabel31.setBounds(53, 291, 12, 26);

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("2");
        Fundo.add(jLabel32);
        jLabel32.setBounds(105, 291, 12, 26);

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("3");
        Fundo.add(jLabel33);
        jLabel33.setBounds(153, 291, 12, 26);

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("4");
        Fundo.add(jLabel34);
        jLabel34.setBounds(200, 291, 12, 26);

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("5");
        Fundo.add(jLabel35);
        jLabel35.setBounds(247, 291, 12, 26);

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("6");
        Fundo.add(jLabel36);
        jLabel36.setBounds(299, 291, 12, 26);

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("7");
        Fundo.add(jLabel37);
        jLabel37.setBounds(351, 291, 12, 26);

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("8");
        Fundo.add(jLabel38);
        jLabel38.setBounds(399, 291, 12, 26);

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("9");
        Fundo.add(jLabel39);
        jLabel39.setBounds(451, 291, 12, 26);

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("10");
        Fundo.add(jLabel40);
        jLabel40.setBounds(495, 291, 24, 26);

        cruzadortxt.setBackground(new java.awt.Color(255, 255, 255));
        cruzadortxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cruzadortxt.setForeground(new java.awt.Color(255, 255, 255));
        cruzadortxt.setText("Cruzador (2x):");
        Fundo.add(cruzadortxt);
        cruzadortxt.setBounds(560, 110, 151, 26);

        posInicialtxt.setBackground(new java.awt.Color(255, 255, 255));
        posInicialtxt.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        posInicialtxt.setForeground(new java.awt.Color(255, 255, 255));
        posInicialtxt.setText("Posição Inicial:");
        Fundo.add(posInicialtxt);
        posInicialtxt.setBounds(670, 10, 151, 26);

        Fcruzador.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Fcruzador.setForeground(new java.awt.Color(102, 102, 102));
        Fcruzador.setText("Ex: A1");
        Fcruzador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fcruzador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FcruzadorMouseClicked(evt);
            }
        });
        Fundo.add(Fcruzador);
        Fcruzador.setBounds(690, 110, 110, 20);

        portaavioestxt.setBackground(new java.awt.Color(255, 255, 255));
        portaavioestxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        portaavioestxt.setForeground(new java.awt.Color(255, 255, 255));
        portaavioestxt.setText("Porta-aviões (4x):");
        Fundo.add(portaavioestxt);
        portaavioestxt.setBounds(560, 50, 151, 26);

        fragatatxt.setBackground(new java.awt.Color(255, 255, 255));
        fragatatxt.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        fragatatxt.setForeground(new java.awt.Color(255, 255, 255));
        fragatatxt.setText("Fragata (3x):");
        Fundo.add(fragatatxt);
        fragatatxt.setBounds(560, 80, 151, 26);

        FportaAvioes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FportaAvioes.setForeground(new java.awt.Color(102, 102, 102));
        FportaAvioes.setText("Ex: A1");
        FportaAvioes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FportaAvioes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FportaAvioesMouseClicked(evt);
            }
        });
        FportaAvioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FportaAvioesActionPerformed(evt);
            }
        });
        Fundo.add(FportaAvioes);
        FportaAvioes.setBounds(690, 50, 110, 20);

        Ffragata.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Ffragata.setForeground(new java.awt.Color(102, 102, 102));
        Ffragata.setText("Ex: A1");
        Ffragata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Ffragata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FfragataMouseClicked(evt);
            }
        });
        Ffragata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FfragataActionPerformed(evt);
            }
        });
        Fundo.add(Ffragata);
        Ffragata.setBounds(690, 80, 110, 20);

        PortaAvioes.add(VportaA);
        VportaA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        VportaA.setForeground(new java.awt.Color(255, 255, 255));
        VportaA.setText("V");
        VportaA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        VportaA.setContentAreaFilled(false);
        VportaA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VportaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VportaAActionPerformed(evt);
            }
        });
        Fundo.add(VportaA);
        VportaA.setBounds(850, 50, 40, 21);

        PortaAvioes.add(HportaA);
        HportaA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        HportaA.setForeground(new java.awt.Color(255, 255, 255));
        HportaA.setSelected(true);
        HportaA.setText("H");
        HportaA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        HportaA.setContentAreaFilled(false);
        HportaA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HportaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HportaAActionPerformed(evt);
            }
        });
        Fundo.add(HportaA);
        HportaA.setBounds(810, 50, 40, 19);

        Fragata.add(Hfragata);
        Hfragata.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Hfragata.setForeground(new java.awt.Color(255, 255, 255));
        Hfragata.setSelected(true);
        Hfragata.setText("H");
        Hfragata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Hfragata.setContentAreaFilled(false);
        Hfragata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hfragata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HfragataActionPerformed(evt);
            }
        });
        Fundo.add(Hfragata);
        Hfragata.setBounds(810, 80, 40, 19);

        Fragata.add(Vfragata);
        Vfragata.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Vfragata.setForeground(new java.awt.Color(255, 255, 255));
        Vfragata.setText("V");
        Vfragata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Vfragata.setContentAreaFilled(false);
        Vfragata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Vfragata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VfragataActionPerformed(evt);
            }
        });
        Fundo.add(Vfragata);
        Vfragata.setBounds(850, 80, 40, 21);

        Cruzador.add(Hcruzador);
        Hcruzador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Hcruzador.setForeground(new java.awt.Color(255, 255, 255));
        Hcruzador.setSelected(true);
        Hcruzador.setText("H");
        Hcruzador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Hcruzador.setContentAreaFilled(false);
        Hcruzador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hcruzador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HcruzadorActionPerformed(evt);
            }
        });
        Fundo.add(Hcruzador);
        Hcruzador.setBounds(810, 110, 40, 19);

        Cruzador.add(Vcruzador);
        Vcruzador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Vcruzador.setForeground(new java.awt.Color(255, 255, 255));
        Vcruzador.setText("V");
        Vcruzador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Vcruzador.setContentAreaFilled(false);
        Vcruzador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Vcruzador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VcruzadorActionPerformed(evt);
            }
        });
        Fundo.add(Vcruzador);
        Vcruzador.setBounds(850, 110, 40, 21);

        IniciarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button.png"))); // NOI18N
        IniciarB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        IniciarB.setContentAreaFilled(false);
        IniciarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarBMouseEntered(evt);
            }
        });
        IniciarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarBActionPerformed(evt);
            }
        });
        Fundo.add(IniciarB);
        IniciarB.setBounds(620, 150, 210, 40);

        closeB.setBackground(new java.awt.Color(255, 255, 255));
        closeB.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        closeB.setForeground(new java.awt.Color(255, 255, 255));
        closeB.setText("X");
        closeB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBMouseExited(evt);
            }
        });
        Fundo.add(closeB);
        closeB.setBounds(860, 10, 20, 16);

        AtacarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AttackButton.png"))); // NOI18N
        AtacarB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        AtacarB.setContentAreaFilled(false);
        AtacarB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fundo.add(AtacarB);
        AtacarB.setBounds(640, 390, 160, 30);

        Fataque.setForeground(new java.awt.Color(102, 102, 102));
        Fataque.setText("Ex: A1");
        Fataque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FataqueMouseClicked(evt);
            }
        });
        Fundo.add(Fataque);
        Fataque.setBounds(640, 350, 160, 22);

        disparartxt.setBackground(new java.awt.Color(255, 255, 255));
        disparartxt.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        disparartxt.setForeground(new java.awt.Color(255, 255, 255));
        disparartxt.setText("Disparo em:");
        Fundo.add(disparartxt);
        disparartxt.setBounds(660, 310, 120, 26);

        exTxt.setBackground(new java.awt.Color(102, 102, 102));
        exTxt.setForeground(new java.awt.Color(102, 102, 102));
        exTxt.setText("Ex: A1");
        Fundo.add(exTxt);
        exTxt.setBounds(700, 330, 43, 16);

        exTxt1.setBackground(new java.awt.Color(102, 102, 102));
        exTxt1.setForeground(new java.awt.Color(102, 102, 102));
        exTxt1.setText("Ex: A1");
        Fundo.add(exTxt1);
        exTxt1.setBounds(730, 30, 43, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void posicionarPlayer() {
        try{
        String pPortaAviao = FportaAvioes.getText();
        String pFragata = Ffragata.getText();
        String pCruzador = Fcruzador.getText();

        //<Separar em coluna e linha>        
        
        String LcPortaAviao = pPortaAviao.substring(0, 1);
        String LlPortaAviao = pPortaAviao.substring(1, pPortaAviao.length());
        
        String LcFragata = pPortaAviao.substring(0, 1);
        String LlFragata = pPortaAviao.substring(1, pFragata.length());
        
        String LcCruzador = pPortaAviao.substring(0, 1);
        String LlCruzador = pPortaAviao.substring(1, pCruzador.length());
        
        
        
        //<Transformar para inteiro>
        
        int cPortaAviao = letraParaNumero(LcPortaAviao);
        int lPortaAviao = Integer.parseInt(LlPortaAviao);
        
        int cFragata = letraParaNumero(LcFragata);
        int lFragata = Integer.parseInt(LlFragata);
        
        int cCruzador = letraParaNumero(LcCruzador);
        int lCruzador = Integer.parseInt(LlCruzador);
        
        //<Validar posicionamento>
        
        if(cPortaAviao == -1 || cFragata == -1 || cCruzador == -1){
            JOptionPane.showMessageDialog(null, "Posição Inexistente!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //<Posicionar PortaAviao>
        
        
        
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Posição Inexistente!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
      
    }
    
    private int letraParaNumero(String var){
        switch (var) {
            case "A":
                return 0;
            case "B":
                return 1;
            case "C":
                return 2;
            case "D":
                return 3;
            case "E":
                return 4;
            default:
                
                return -1;
        }
    }


    private void VportaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VportaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VportaAActionPerformed

    private void HportaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HportaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HportaAActionPerformed

    private void HfragataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HfragataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HfragataActionPerformed

    private void VfragataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VfragataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VfragataActionPerformed

    private void HcruzadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HcruzadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HcruzadorActionPerformed

    private void VcruzadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VcruzadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VcruzadorActionPerformed

    private void IniciarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarBActionPerformed

    private void IniciarBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarBMouseClicked
        try{
        if (Ffragata.getText().contains("Ex: A1")
            || FportaAvioes.getText().contains("Ex: A1")
            || Fcruzador.getText().contains("Ex: A1")) 
        {
            JOptionPane.showMessageDialog(null, "Preencha todas as posições!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{

        posicionarPlayer();
        }
        }
        catch(StringIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Preencha todas as posições!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_IniciarBMouseClicked

    private void closeBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBMouseEntered
        closeB.setForeground(Color.red);
    }//GEN-LAST:event_closeBMouseEntered

    private void closeBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBMouseExited
        closeB.setForeground(Color.white);
    }//GEN-LAST:event_closeBMouseExited

    private void closeBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBMouseClicked
        dispose();
        TelaInicial inicio = new TelaInicial();
        inicio.setVisible(true);
    }//GEN-LAST:event_closeBMouseClicked

    private void IniciarBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarBMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_IniciarBMouseEntered

    private void FfragataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FfragataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FfragataActionPerformed

    private void FportaAvioesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FportaAvioesMouseClicked
        if (FportaAvioes.getText().contains("Ex: A1")) {
            FportaAvioes.setText(null);
            FportaAvioes.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_FportaAvioesMouseClicked

    private void FfragataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FfragataMouseClicked
        if (Ffragata.getText().contains("Ex: A1")) {
            Ffragata.setText(null);
            Ffragata.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_FfragataMouseClicked

    private void FcruzadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FcruzadorMouseClicked
        if (Fcruzador.getText().contains("Ex: A1")) {
            Fcruzador.setText(null);
            Fcruzador.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_FcruzadorMouseClicked

    private void FataqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FataqueMouseClicked
        if (Fataque.getText().equalsIgnoreCase("Ex: A1")) {
            Fataque.setText(null);
            Fataque.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_FataqueMouseClicked

    private void FportaAvioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FportaAvioesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FportaAvioesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static javax.swing.JPanel CriarQuadrados1(int vX, int vY) {
        int t = 50;
        javax.swing.JPanel Quadrado = new javax.swing.JPanel();
        Quadrado.setSize(50, 50);
        Quadrado.setBackground(Color.white);
        Quadrado.setLocation(33 + (t * vX), 33 + (t * vY));
        Quadrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Quadrado.setVisible(true);
        return Quadrado;
    }

    public static javax.swing.JPanel CriarQuadrados2(int vX, int vY) {
        int t = 50;
        javax.swing.JPanel Quadrado = new javax.swing.JPanel();
        Quadrado.setSize(50, 50);
        Quadrado.setBackground(Color.white);
        Quadrado.setLocation(33 + (t * vX), 317 + (t * vY));
        Quadrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Quadrado.setVisible(true);
        return Quadrado;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtacarB;
    private javax.swing.ButtonGroup Cruzador;
    private javax.swing.JTextField Fataque;
    private javax.swing.JTextField Fcruzador;
    private javax.swing.JTextField Ffragata;
    private javax.swing.JTextField FportaAvioes;
    private javax.swing.ButtonGroup Fragata;
    private static javax.swing.JPanel Fundo;
    private javax.swing.JRadioButton Hcruzador;
    private javax.swing.JRadioButton Hfragata;
    private javax.swing.JRadioButton HportaA;
    private javax.swing.JButton IniciarB;
    private javax.swing.ButtonGroup PortaAvioes;
    private javax.swing.JRadioButton Vcruzador;
    private javax.swing.JRadioButton Vfragata;
    private javax.swing.JRadioButton VportaA;
    private javax.swing.JLabel closeB;
    private javax.swing.JLabel cruzadortxt;
    private javax.swing.JLabel disparartxt;
    private javax.swing.JLabel exTxt;
    private javax.swing.JLabel exTxt1;
    private javax.swing.JLabel fragatatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel portaavioestxt;
    private javax.swing.JLabel posInicialtxt;
    // End of variables declaration//GEN-END:variables

}
