/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalhanaval;

import java.awt.Color;

/**
 *
 * @author l a w t
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExitB = new javax.swing.JButton();
        PlayB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(888, 600));
        getContentPane().setLayout(null);

        ExitB.setBackground(new java.awt.Color(0, 0, 0));
        ExitB.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        ExitB.setForeground(new java.awt.Color(102, 102, 102));
        ExitB.setText("Exit");
        ExitB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ExitB.setContentAreaFilled(false);
        ExitB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBMouseExited(evt);
            }
        });
        ExitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBActionPerformed(evt);
            }
        });
        getContentPane().add(ExitB);
        ExitB.setBounds(170, 420, 140, 40);

        PlayB.setBackground(new java.awt.Color(0, 0, 0));
        PlayB.setFont(new java.awt.Font("Wide Latin", 0, 36)); // NOI18N
        PlayB.setForeground(new java.awt.Color(102, 102, 102));
        PlayB.setText("Play");
        PlayB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        PlayB.setContentAreaFilled(false);
        PlayB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PlayB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PlayBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlayBMouseExited(evt);
            }
        });
        PlayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayBActionPerformed(evt);
            }
        });
        getContentPane().add(PlayB);
        PlayB.setBounds(100, 320, 270, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TelaInicial.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(888, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 888, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitBActionPerformed

    private void ExitBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBMouseEntered
        ExitB.setBounds(155, 405, 170, 70);
        ExitB.setForeground(Color.red);
        ExitB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        ExitB.setFont(new java.awt.Font("Wide Latin", 0, 22));
    }//GEN-LAST:event_ExitBMouseEntered

    private void ExitBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBMouseExited
        ExitB.setBounds(170, 420, 140, 40);
        ExitB.setForeground(new java.awt.Color(102, 102, 102));
        ExitB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ExitB.setFont(new java.awt.Font("Wide Latin", 0, 18));
    }//GEN-LAST:event_ExitBMouseExited

    private void PlayBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayBMouseEntered
        PlayB.setBounds(85, 305, 300, 90);
        PlayB.setForeground(Color.white);
        PlayB.setFont(new java.awt.Font("Wide Latin", 0, 40));
    }//GEN-LAST:event_PlayBMouseEntered

    private void PlayBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayBMouseExited
        PlayB.setBounds(100, 320, 270, 60);
        PlayB.setForeground(new java.awt.Color(102, 102, 102));
        PlayB.setFont(new java.awt.Font("Wide Latin", 0, 36));
    }//GEN-LAST:event_PlayBMouseExited

    private void PlayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlayBActionPerformed

    private void PlayBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayBMouseClicked
        Jogo game = new Jogo();
        this.dispose();
        game.setVisible(true);
    }//GEN-LAST:event_PlayBMouseClicked

    private void ExitBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBMouseClicked
        this.dispose();
    }//GEN-LAST:event_ExitBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitB;
    private javax.swing.JButton PlayB;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
